import { wb, type WorkbenchExample } from '@atlassian/workbench';

import BoardWithMultiDragExample from './board-with-multi-drag';
import BoardWithOverflowScrollExample from './board-with-overflow-scroll';
import BoardVrExample from './board.vr.ap';
import ChessExample from './chess';
import DeferredExample from './deferred';
import DragHandleButtonExample from './drag-handle-button';
import DragHandlesExample from './drag-handles';
import DrawingExample from './drawing';
import FileExample from './file';
import FileDropWithoutPragmaticExample from './file-drop-without-pragmatic';
import FlashPrototypeExample from './flash-prototype';
import GridVrExample from './grid.vr.ap';
import GuidelinesExample from './guidelines';
import IframeBoardExample from './iframe-board';
import IframeColumnExample from './iframe-column';
import ListComparisonExample from './list-comparison';
import ListVrExample from './list.vr.ap';
import ManualFocusRestorationExample from './manual-focus-restoration';
import NestedDraggablesExample from './nested-draggables';
import NestedDropTargetsExample from './nested-drop-targets';
import ResizingExample from './resizing';
import TableVrExample from './table.vr.ap';
import TextSelectionExample from './text-selection';
import TreeLegacyExample from './tree-legacy';
import TreeVrExample from './tree.vr.ap';
import VirtualListExample from './virtual-list';

export const BoardWithMultiDrag: WorkbenchExample = wb(BoardWithMultiDragExample);
export const BoardWithOverflowScroll: WorkbenchExample = wb(BoardWithOverflowScrollExample);
export const BoardVr: WorkbenchExample = wb(BoardVrExample);
export const Chess: WorkbenchExample = wb(ChessExample);
export const Deferred: WorkbenchExample = wb(DeferredExample);
export const DragHandleButton: WorkbenchExample = wb(DragHandleButtonExample);
export const DragHandles: WorkbenchExample = wb(DragHandlesExample);
export const Drawing: WorkbenchExample = wb(DrawingExample);
export const File: WorkbenchExample = wb(FileExample);
export const FileDropWithoutPragmatic: WorkbenchExample = wb(FileDropWithoutPragmaticExample);
export const FlashPrototype: WorkbenchExample = wb(FlashPrototypeExample);
export const GridVr: WorkbenchExample = wb(GridVrExample);
export const Guidelines: WorkbenchExample = wb(GuidelinesExample);
export const IframeBoard: WorkbenchExample = wb(IframeBoardExample);
export const IframeColumn: WorkbenchExample = wb(IframeColumnExample);
export const ListComparison: WorkbenchExample = wb(ListComparisonExample);
export const ListVr: WorkbenchExample = wb(ListVrExample);
export const ManualFocusRestoration: WorkbenchExample = wb(ManualFocusRestorationExample);
export const NestedDraggables: WorkbenchExample = wb(NestedDraggablesExample);
export const NestedDropTargets: WorkbenchExample = wb(NestedDropTargetsExample);
export const Resizing: WorkbenchExample = wb(ResizingExample);
export const TableVr: WorkbenchExample = wb(TableVrExample);
export const TextSelection: WorkbenchExample = wb(TextSelectionExample);
export const TreeLegacy: WorkbenchExample = wb(TreeLegacyExample);
export const TreeVr: WorkbenchExample = wb(TreeVrExample);
export const VirtualList: WorkbenchExample = wb(VirtualListExample);
